### PR TITLE
Dependency Updates

### PR DESCRIPTION
**Pull request by vivekkiran**

### CODE REVIEW

**Comment by jaydeepw** [comment]
THanks for the PR @vivekkiran . You Rock!
Next time, submit PR on develop branch.
I will look into it soon.

**Comment by jaydeepw** [comment]
May I know which JDK version are you using? It fails to compile saying gradle has issue compiling with my JDK version 1.7.0_75 and asks me to download _67

**Comment by vivekkiran** [comment]
I am using jdk1.7.0_75 and that day I pushed 2 commits and accidentally the second commit I did was force push. I'll look into the code again and send another PR in dev branch.

**Comment by vivekkiran** [comment]
And it will be good if we can integrate Travis CI , so that every pull request will go through an automated build system and and log output its free for open source projects and very easy to integrate.

**Pull request merged**
